check route before checking host

diff --git a/wfs b/wfs
--- a/wfs
+++ b/wfs
@@ -7,7 +7,7 @@
 # Licence = GNU GPL
 #
 
-VERSION=2.05
+VERSION=2.05a
 
 CONFIG=/etc/wfs
 CONFIG_FILE="$CONFIG/wfs.conf"
@@ -104,6 +104,36 @@ log2syslog () {
     echo "$MSG" | logger -t "WFS" -p daemon."$TYPE"
 }
 
+remove_target_routes() {
+    for x in $TARGETS
+    do
+        log DEBUG "Removing static route for host $x"
+        route del -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
+    done
+}
+
+add_target_routes () {
+    # cleanup routes before, sometimes something is left over
+    remove_target_routes
+    
+    # add routes
+    for x in $TARGETS
+    do
+      log DEBUG "Adding static route for host $x"
+      ROUTE_ADDED=-1
+      while [ $ROUTE_ADDED -ne "0" ]
+      do
+        route add -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
+        ROUTE_ADDED=$?
+        if [ $ROUTE_ADDED -ne "0" ]
+        then
+          log ERROR "failed to route add -host $x gw $PRIMARY_GW, retrying in $INTERVAL seconds"
+          sleep $INTERVAL
+        fi
+      done
+    done
+}
+
 init_wfs () {
 
     if [ ! -e "$TARGETS_FILE" ]
@@ -121,21 +151,7 @@ init_wfs () {
         log ERROR "No targets to test availability, targets file $TARGETS_FILE empty?."
         exit 1
     else
-        for x in $TARGETS
-        do
-            log DEBUG "Adding static route for host $x"
-            ROUTE_ADDED=-1
-            while [ $ROUTE_ADDED -ne "0" ]
-            do
-              route add -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
-              ROUTE_ADDED=$?
-              if [ $ROUTE_ADDED -ne "0" ]
-              then
-                log ERROR "failed to route add -host $x gw $PRIMARY_GW, retrying in $INTERVAL seconds"
-                sleep $INTERVAL
-              fi
-            done
-        done
+        add_target_routes
     fi
 }
 
@@ -161,7 +177,7 @@ display_header () {
     log INFO "------------------------------"
     log INFO " Primary gateway: $PRIMARY_GW"
     log INFO " Secondary gateway: $SECONDARY_GW"
-    log INFO " Max latency in ms: $MAX_LATENCY"
+    log INFO " Max latency in s: $MAX_LATENCY"
     log INFO " Threshold before failover: $THRESHOLD"
     log INFO " Number of target hosts: $NO_OF_TARGETS"
     log INFO " Tests per host: $TEST_COUNT"
@@ -174,10 +190,24 @@ display_header () {
 # Is available again, when in failover mode.
 #
 
+check_route () {
+    TARGET="$1"
+
+    log DEBUG "checking route to $TARGET"
+    (ip route 2>&1 | grep "^$TARGET via $PRIMARY_GW") >> /dev/null 2>&1
+    if [ ! "$?" = "0" ]
+    then
+        log INFO "recreating routes ($TARGET via $PRIMARY_GW missing)"
+        add_target_routes
+    fi
+}
 
 test_single_target () {
 
     TARGET="$1"
+     
+    check_route $TARGET
+
     log DEBUG "Test interval between hosts is $TEST_INTERVAL"
 
     ping -W "$MAX_LATENCY" -c "$TEST_COUNT" "$TARGET" >> /dev/null 2>&1
@@ -250,7 +280,7 @@ check_wan_status () {
 	    switch
         fi
     else
-        log INFO "WAN Link: $ACTIVE_CONNECTION"
+        log DEBUG "WAN Link: $ACTIVE_CONNECTION"
     fi
 }
 
@@ -310,11 +340,7 @@ stop_wfs () {
 
     if [ ! -z "$TARGETS" ]
     then
-        for x in $TARGETS
-        do
-            log DEBUG "Removing static route for host $x"
-            route del -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
-        done
+      remove_target_routes
     fi
 
     exit 0
